import { RoutePermittedRole } from '@/app/constants/AppEnums';
import {
  FcAlarmClock,
  FcAssistant,
  FcBriefcase,
  FcBullish,
  FcBusinessman,
  FcFeedback,
  FcHighPriority,
  FcInspection,
  FcLibrary,
  FcLineChart,
  FcManager,
  FcOk,
  FcOpenedFolder,
  FcPlanner,
  FcRatings,
  FcServices,
} from 'react-icons/fc';

import { MODULE } from '@/lib/helpers/authHelpers';
import Award from '../../../../public/icons/award';
import Brain from '../../../../public/icons/brain';
import { DashboardIcons } from '../../../../public/icons/dashboard';
import Key from '../../../../public/icons/key';
import Pen from '../../../../public/icons/pen';
import People from '../../../../public/icons/people';
import { School } from '../../../../public/icons/school';
import Setting from '../../../../public/icons/setting';
import Timetable from '../../../../public/icons/timetable';
import Write from '../../../../public/icons/write';

const routesConfig = [
  {
    id: MODULE.DASHBOARD,
    title: 'dashboard',
    messageId: 'sidebar.sample.dashboard',
    type: 'item',
    icon: <DashboardIcons />,
    url: '/dashboard',
    roles: [
      RoutePermittedRole.SuperAdmin,
      RoutePermittedRole.Admin,
      RoutePermittedRole.Teacher,
      RoutePermittedRole.Parent,
      RoutePermittedRole.Student,
      RoutePermittedRole.DEPARTMENT_OF_EDUCATION,
      RoutePermittedRole.DEPARTMENT_OF_EDUCATION,
    ],
  },
  {
    id: MODULE.INSTITUTE,
    title: 'school',
    messageId: 'sidebar.institutes',
    url: '/school/list',
    icon: <School />,
    roles: [
      RoutePermittedRole.SuperAdmin,
      RoutePermittedRole.Admin,
      RoutePermittedRole.Teacher,
      RoutePermittedRole.Parent,
      RoutePermittedRole.Student,
      RoutePermittedRole.DEPARTMENT_OF_EDUCATION,
    ],
  },
  // {
  //   id: 'upgrade-student',
  //   title: 'upgrade-student',
  //   messageId: 'sidebar.upgrade-student',
  //   type: 'item',
  //   icon: <Write />,
  //   url: '/upgrade-student',
  //   roles: [
  //     RoutePermittedRole.SuperAdmin,
  //     RoutePermittedRole.Admin,
  //     RoutePermittedRole.Teacher,
  //     RoutePermittedRole.Parent,
  //     RoutePermittedRole.Student,
  //   ],
  // },
  // {
  //   id: 'upgrade-teacher',
  //   title: 'upgrade-teacher',
  //   messageId: 'sidebar.upgrade-teacher',
  //   type: 'item',
  //   icon: <Write />,
  //   url: '/upgrade-teacher',
  //   roles: [
  //     RoutePermittedRole.SuperAdmin,
  //     RoutePermittedRole.Admin,
  //     RoutePermittedRole.Teacher,
  //     RoutePermittedRole.Parent,
  //     RoutePermittedRole.Student,
  //   ],
  // },
  {
    id: 'ignore-protected-master',
    title: 'Users',
    messageId: 'sidebar.management',
    icon: <People />,
    roles: [
      RoutePermittedRole.SuperAdmin,
      RoutePermittedRole.Admin,
      RoutePermittedRole.Teacher,
      RoutePermittedRole.Parent,
      RoutePermittedRole.Student,
      RoutePermittedRole.DEPARTMENT_OF_EDUCATION,
    ],
    type: 'collapse',
    children: [
      {
        id: MODULE.ADMIN,
        title: 'admin',
        messageId: 'sidebar.admin',
        url: '/admin/list',
        icon: <FcLibrary size={25} />,
      },
      {
        id: MODULE.TEACHERS,
        title: 'teacher',
        messageId: 'sidebar.teachers',
        url: '/teacher/list',
        icon: <FcAssistant size={25} />,
      },
      {
        id: MODULE.STUDENTS,
        title: 'learner',
        messageId: 'sidebar.students',
        url: '/learner/list',
        icon: <FcBusinessman size={20} />,
      },
      {
        id: MODULE.PARENTS,
        title: 'parent',
        messageId: 'sidebar.parents',
        url: '/parent/list',
        icon: <FcManager size={20} />,
      },
      {
        id: MODULE.DEPARTMENT_OF_EDUCATION,
        title: 'departmentadmin',
        messageId: 'sidebar.departmentofeducation',
        url: '/department-admin/list',
        icon: <FcBriefcase size={25} />,
      },
    ],
  },
  // {
  //   id: MODULE.ASSESSMENTS,
  //   title: 'exams',
  //   messageId: 'sidebar.exams',
  //   type: 'item',
  //   icon: <Write />,
  //   url: '/assessments',
  //   roles: [
  //     RoutePermittedRole.SuperAdmin,
  //     RoutePermittedRole.Admin,
  //     RoutePermittedRole.Teacher,
  //     RoutePermittedRole.Parent,
  //     RoutePermittedRole.Student,
  //   ],
  // },
  {
    id: 'ignore-protected-digital-marking',
    title: 'digitalMarking',
    messageId: 'sidebar.digitalmarketing',
    roles: [
      RoutePermittedRole.SuperAdmin,
      RoutePermittedRole.Admin,
      RoutePermittedRole.Teacher,
      RoutePermittedRole.Parent,
      RoutePermittedRole.Student,
      RoutePermittedRole.DEPARTMENT_OF_EDUCATION,
    ],
    type: 'collapse',
    icon: <Pen />,
    children: [
      {
        id: MODULE.ASSESSMENTS,
        title: 'assessments',
        messageId: 'sidebar.exams',
        url: '/assessments',
        icon: <Write />,
      },
      {
        id: MODULE.GRADING_PROCESS,
        title: 'gradingprocess',
        messageId: 'sidebar.gradingProcess',
        url: '/grading-process',
        icon: <FcFeedback size={25} />,
      },
      // {
      //   id: MODULE.MEMO,
      //   title: 'memos',
      //   messageId: 'sidebar.memos',
      //   url: '/memo',
      //   icon: <FcFeedback size={25} />,
      // },
      {
        id: MODULE.MANUAL_REVIEW,
        title: 'manualreview',
        messageId: 'sidebar.manualreview',
        url: '/manual-review',
        icon: <FcInspection size={25} />,
      },
      {
        id: MODULE.MARKED_ANSWER_SCRIPTS,
        title: 'markedanswerscript',
        messageId: 'sidebar.sample.gradedPapers',
        url: '/marked-answerscript',
        icon: <FcOk size={25} />,
      },
      // {
      //   id: MODULE.ANSWERSCRIPT,
      //   title: 'answerScripts',
      //   messageId: 'sidebar.answerscripts',
      //   url: '/answer-scripts',
      //   icon: <FcFile size={25} />,
      // },
    ],
  },
  {
    id: 'ignore-protected-result-portal',
    title: 'ResultsPortal',
    messageId: 'sidebar.sample.resultsportal',
    type: 'collapse',
    icon: <Award />,
    roles: [
      RoutePermittedRole.SuperAdmin,
      RoutePermittedRole.Admin,
      RoutePermittedRole.Teacher,
      RoutePermittedRole.Parent,
      RoutePermittedRole.Student,
      RoutePermittedRole.DEPARTMENT_OF_EDUCATION,
    ],
    children: [
      {
        id: 'ignore-protected-results',
        title: 'result',
        messageId: 'sidebar.sample.resultsportal.resultsportaldashboard',
        url: '/result/dashboard',
        icon: <FcBullish size={25} />,
      },
      // {
      //   id: MODULE.RESULT_DASHBOARD,
      //   title: 'results',
      //   messageId: 'sidebar.sample.resultsportal.grades',
      //   url: '/results/all',
      //   icon: <FcViewDetails size={25} />,
      // },
      {
        id: MODULE.REPORT_CARD,
        title: 'grouped',
        messageId: 'sidebar.sample.resultsportal.reportcard',
        url: '/grouped',
        icon: <FcHighPriority size={25} />,
      },
    ],
  },
  {
    id: 'ignore-protected-study-material',
    title: 'PersonalizedLearning',
    messageId: 'sidebar.personalizedlearning',
    type: 'collapse',
    icon: <Brain />,
    roles: [
      RoutePermittedRole.SuperAdmin,
      RoutePermittedRole.Admin,
      RoutePermittedRole.Teacher,
      RoutePermittedRole.Parent,
      RoutePermittedRole.Student,
      RoutePermittedRole.DEPARTMENT_OF_EDUCATION,
    ],
    children: [
      {
        id: MODULE.PRACTICE_EXERCISES,
        title: 'practice',
        messageId: 'sidebar.personalizedlearning.practice',
        url: '/practice',
        icon: <FcLineChart size={25} />,
      },
      {
        id: MODULE.LESSON_PLAN,
        title: 'lessonplan',
        messageId: 'sidebar.personalizedlearning.teacherlessionplan',
        url: '/lesson-plan',
        icon: <FcHighPriority size={25} />,
      },

      {
        id: MODULE.STUDY_MATERIAL,
        title: 'studymaterial',
        messageId: 'sidebar.personalizedlearning.studymatrial',
        url: '/study-material',
        icon: <FcOpenedFolder size={25} />,
      },
    ],
  },
  {
    id: 'ignore-protected-events',
    title: 'Events',
    messageId: 'sidebar.sample.calendar',
    type: 'collapse',
    icon: <FcPlanner size={25} />,
    roles: [
      RoutePermittedRole.SuperAdmin,
      RoutePermittedRole.Admin,
      RoutePermittedRole.Teacher,
      RoutePermittedRole.Parent,
      RoutePermittedRole.Student,
      RoutePermittedRole.DEPARTMENT_OF_EDUCATION,
    ],
    children: [
      {
        id: MODULE.CALENDAR,
        title: 'calendar',
        messageId: 'sidebar.sample.events',
        type: 'item',
        icon: <Timetable />,
        url: '/calendar',
        roles: [
          RoutePermittedRole.SuperAdmin,
          RoutePermittedRole.Admin,
          RoutePermittedRole.Teacher,
          RoutePermittedRole.Parent,
          RoutePermittedRole.Student,
        ],
      },
      {
        id: MODULE.EXAM_TIME_TABLE,
        title: 'assessmenttimetable',
        messageId: 'sidebar.sample.examtimetable',
        type: 'item',
        icon: <FcAlarmClock size={25} />,
        url: '/assessment-timetable',
        roles: [
          RoutePermittedRole.SuperAdmin,
          RoutePermittedRole.Admin,
          RoutePermittedRole.Teacher,
          RoutePermittedRole.Parent,
          RoutePermittedRole.Student,
        ],
      },
    ],
  },
  {
    id: MODULE.REPORT_MANAGEMENT,
    title: 'reportmanagement',
    messageId: 'sidebar.sample.reportmanagement',
    type: 'item',
    icon: <FcRatings />,
    url: '/report-management',
    roles: [
      RoutePermittedRole.SuperAdmin,
      RoutePermittedRole.Admin,
      RoutePermittedRole.Teacher,
      RoutePermittedRole.Parent,
      RoutePermittedRole.Student,
      RoutePermittedRole.DEPARTMENT_OF_EDUCATION,
    ],
  },
  {
    id: 'ignore-protected-role-management',
    title: 'module',
    messageId: 'sidebar.sample.rolemanagement',
    type: 'item',
    icon: <Key />,
    url: '/module/select',
    roles: [RoutePermittedRole.SuperAdmin],
  },
  {
    id: 'ignore-protected-settings',
    title: 'main-settings',
    messageId: 'sidebar.settings',
    type: 'collapse',
    icon: <Setting />,
    roles: [
      RoutePermittedRole.SuperAdmin,
      RoutePermittedRole.Admin,
      RoutePermittedRole.Teacher,
      RoutePermittedRole.Parent,
      RoutePermittedRole.Student,
      RoutePermittedRole.DEPARTMENT_OF_EDUCATION,
    ],
    children: [
      {
        id: MODULE.GENERAL_SETTINGS,
        title: 'settings',
        messageId: 'sidebar.sample.generalsettings',
        type: 'item',
        icon: <FcServices />,
        url: '/settings',
        roles: [
          RoutePermittedRole.SuperAdmin,
          RoutePermittedRole.Admin,
          RoutePermittedRole.Teacher,
          RoutePermittedRole.Parent,
          RoutePermittedRole.Student,
        ],
      },
    ],
  },
];

export default routesConfig;
