export const NEST_API_ENDPOINT = import.meta.env.VITE_API_ENDPOINT;
export const JANGO_API_ENDPOINT = import.meta.env.VITE_JANGO_API_ENDPOINT;
export const JANGO_PDF_ENDPOINT = import.meta.env.VITE_JANGO_PDF_ENDPOINT;
export const VITE_SCHOOL_LOGO_URL = import.meta.env.VITE_SCHOOL_LOGO_URL;

// TODO: Make all of this Screaming snake case
const API = Object.freeze({
  AUTH: {
    LOGIN: 'auth/login',
    LOGOUT: '',
    FORGET_PASSWORD: 'auth/forgot-password',
    RESET_PASSWORD: 'auth/reset-password',
    CHANGE_PASSWORD: 'auth/change-password',
    RE_LOGIN: 'auth/re-login',
    CHECK_IF_VERIFIED: 'auth/verify-user',
  },
  USER: {
    DETAIL: 'users/',
  },
  DASHBOARD: {
    LIST: '',
  },
  INSTITUTE: {
    LIST: 'institute/list',
    ADD: 'institute/create',
    DETAILS: 'institute/',
    UPDATE: 'institute/patch/',
    DELETE: 'institute/delete/',
  },
  ADMIN: {
    LIST: 'admin/list',
    ADD: 'admin/create',
    ADMIN_DATA_GET_BY_ID: 'admin/',
    UPDATE: 'admin/patch/',
    DELETE: 'admin/delete/',
  },
  TEACHER: {
    LIST: 'teacher/list',
    ADD: 'teacher/create',
    TEACHER_DATA_GET_BY_ID: 'teacher/',
    TEACHER_SUBJECTLIST_GET_BY_ID: 'teacher/teacher-assign-subject/',
    UPDATE: 'teacher/patch/',
    DELETE: 'teacher/delete/',
  },
  STUDENT: {
    LIST: 'student/list',
    PARENT_STUDENT_LIST: '/parent/student-list',
    ADD: 'student/create',
    STUDENT_LIST_GET_BY_ID: 'student/',
    UPDATE: 'student/patch/',
    DELETE: 'student/delete/',
    SUBJECT_WISE: 'student/subject-by/list',
    DETAILS: 'student/',
    DELETE_PARENTS_FROM_LEARNER: 'parent/remove-parent-from-student',
  },
  EXAMS: {
    LIST: 'exam',
    ADD: 'exam/create',
    EXAM_LIST_GET_BY_ID: 'exam/',
    UPDATE: 'exam/',
    DELETE: 'exam/',
  },
  PARENT: {
    LIST: 'parent/list',
    ADD: 'parent/create',
    PARENT_DATA_GET_BY_ID: 'parent/',
    UPDATE: 'parent/patch/',
    DELETE: 'parent/delete/',
  },
  DOE: {
    DOE_LIST: 'department-user/list',
    DOE_CREATE: 'department-user/create',
    DOE_DATA_GET_BY_ID: 'department-user/',
    UPDATE: 'department-user/patch/',
    DELETE: 'department-user/delete/',
  },
  DIVISION: {
    LIST: 'division/list',
    MULTI_ADD: 'division/multi/create',
    ADD: 'division/create',
    DETAILS: 'division/',
    UPDATE: 'division/patch/',
    DELETE: 'division/delete/',
  },
  CITY: {
    LIST: 'city/list/',
  },
  STATE: {
    LIST: 'state/list',
  },
  PERMISSION: {
    LIST: 'permissions/list',
    ADD: 'permissions/create',
    UPDATE: 'permissions/patch/',
    DELETE: 'permissions/delete/',
    DETAILS: 'permissions/',
  },
  MODULE: {
    LIST: 'module/list',
  },
  SETTINGS: {
    LIST: 'settings/list',
    ADD: 'settings/create',
    DETAILS: 'settings/',
    UPDATE: 'settings/patch/',
    DELETE: 'settings/delete/',
  },
  USER_ROLE: {
    LIST: 'role/list',
    ADD: 'role/create',
    DETAILS: 'role/',
    UPDATE: 'role/patch/',
    DELETE: 'role/delete/',
  },
  MANUAL_REVIEW: {
    DETAILS: 'answersheet-marks/',
    UPDATE: 'answersheet-marks/update-mark/',
    FINAL_SUBMIT: 'student-answersheet/reviewed/',
  },
  SETUP: {
    BATCH: 'batch/create',
    GET_STATUS: 'school-setup/status',
    UPDATE_STATUS: 'school-setup/update',
    BATCH_SETUP: 'batch/update-batch-for-setup-wizard',
    GRADE_SETUP: 'grade/create-for-setup-wizard',
    DIVISION_SETUP: 'division/manage-division-for-setup-wizard',
  },
  GRADE: {
    LIST: 'grade/list',
    ADD: 'grade/create',
    MULTI_ADD: 'grade/multi/create',
    DETAILS: 'grade/',
    UPDATE: 'grade/patch/',
    DELETE: 'grade/delete/',
  },
  BULK_UPLOAD: {
    SINGLE_UPLOAD: 'student-answersheet/',
    SINGLE_UPLOAD_DELETE: 'student-answersheet/',
    BULK_UPLOAD: 'student-answersheet/bulk-upload',
    CHANGE_MEMO: 'assessments-subjects/update-memo/',
    CHANGE_QUESTION: 'assessments-subjects/update-question-paper/',
    BULK_UPLOAD_DETAILS: 'bulkupload/',
    BULK_UPLOAD_UPDATE: 'bulkupload/patch/',
    BULK_UPLOAD_DELETE: 'bulkupload/delete/',
  },
  ROLE_BASE_PERMISSION: {
    LIST: 'permissions/list',
    ADD: 'permissions/create',
    UPDATE: 'permissions/patch/',
    DELETE: 'permissions/delete/',
    DETAILS: 'permissions/',
  },
  SUBJECT: {
    LIST: 'subject/list',
    MULTI_ADD: 'subject/multi/create',
    ADD: 'subject/create',
    DELETE: 'subject/delete/',
    DETAILS: 'subject/',
  },
  MASTER_SUBJECT: {
    LIST: 'master-subject/list',
  },
  DIVISION_SUBJECT: {
    LIST: 'division-subject/list',
    TEACHER_SETUP: 'division-subject/teacher/setup',
    DELETE: 'division-subject/delete/',
    CREATE: 'division-subject/create',
    LEARNER_TEACHER_LIST: 'division-subject/learner-teacher-list/',
  },
  QUIZ: {
    LIST: 'quiz/',
    CREATE_MANUAL_QUIZ: 'quiz/',
    QUIZ_DETAILS: 'quiz/main-quiz/',
    MAIN_QUIZ: 'quiz/main-quiz/',
    ATTEMPT_QUIZ: 'quiz/attempt-quiz/',
    GENERATE_QUIZ: 'quiz/generate-quiz/',
    GENERATE_SELF_QUIZ: 'quiz/generate-self-quiz/',
    STUDENT_STATS: 'quiz/student-stats/',
    RETRIEVE_QUIZ: 'quiz/',
    STRENGTH_AND_WEAKNESS: 'quiz/strengths-weaknesses/',
    UPDATE_QUIZ: 'quiz/',
  },
  BATCH: {
    LIST: 'batch/list',
    ADD: 'batch/create',
    DETAILS: 'batch/',
    UPDATE: 'batch/patch/',
    DELETE: 'batch/delete/',
    ACTIVE: 'batch/active',
  },
  TERM: {
    LIST: 'term/list',
    ADD: 'term/create',
    DETAILS: 'term/',
    UPDATE: 'term/patch/',
    DELETE: 'term/delete/',
  },
  ASSESSMENT: {
    LIST: 'assessments/',
    ADD: 'assessments/',
    UPDATE: 'assessments/',
    DELETE: 'assessments/',
  },
  ANALYTICS: {
    ANALYTICS: 'assessment-analytics/',
    STUDENT_ANALYTICS: 'assessment-analytics/student-analytics/',
    ANSWERSHEET_MARKS: 'answersheet-marks/result/',
    STRENGTHS_AND_WEAKNESSES: 'assessment-analytics/strength-weakness/',
  },
  SUBJECT_WISE_ASSESSMENT: {
    LIST: 'assessments-subjects/',
    ADD: 'assessments-subjects/',
    UPDATE: 'assessments-subjects/',
    DELETE: 'assessments-subjects/',
  },
  ASSESSMENTS_DETAILS: {
    LIST: 'assessments/',
  },
  STUDENTS_LIST: {
    LIST: 'student-answersheet/',
  },
  OCR_START: {
    LIST: 'student-answersheet/start-checking/',
  },
  DOWNLOAD_COVER_PAGE: {
    GET: 'assessments-subjects/generate-cover-paper/',
    DELETE: 'assessments-subjects/delete-cover-paper/',
  },
  EVENT: {
    LIST: 'event/list',
    ADD: 'event/multi-create',
    EVENT_DATA_GET_BY_ID: 'event/',
    UPDATE: 'event/update/',
    DELETE: 'event/delete/',
  },
  NOTIFICATION: {
    LIST: 'notification/list',
    ADD: 'notification/create',
    NOTIFICATION_DATA_GET_BY_ID: 'notification/',
    UPDATE: 'notification/update/',
    DELETE: 'notification/delete/',
    READ_ALL: 'notification/read-all',
    UNREAD_COUNT: 'notification/unread-count'
  },
  AUDIT_LOG: {
    LIST: 'audit-log/list',
  },
  MASTER_SUBJECT_CRUD: {
    LIST: 'master-subject/list',
    ADD: 'master-subject/multi/create',
    GET_DETAIL_BY_ID: 'master-subject/',
    UPDATE: 'master-subject/patch/',
    DELETE: 'master-subject/delete/',
  },
  LESSON_PLAN: {
    LIST: 'lesson-plans/',
    ADD: 'lesson-plans/',
    GET_DETAIL_BY_ID: 'lesson-plans/',
    UPDATE: 'lesson-plans/',
    DELETE: 'lesson-plans/',
  },
  GENERAL_SETTING: {
    ADD: 'general-setting/updated',
    DETAIL: 'general-setting/general-setting',
    REMOVE_LOGO: 'general-setting/remove-logo',
  },
  DASHBOARD_CHART: {
    STUDENT_PER_GRADE: 'dashboard/student-per-grade/',
    NUMBER_OF_TEACHERS_IN_GRADE: 'dashboard/teachers-per-grade/',
    NUMBER_OF_STUDENTS_IN_SUBJECT: 'dashboard/students-per-subject/',
    SUBJECT_PASS_FAIL_RATE: 'dashboard/subject-pass-fail-rate/',
    USER_COUNT: 'dashboard/user-counts/',
    ASSESSMENT_ANALYTICS: 'dashboard/assessments-analytics/',
    SUBJECT_QUIZ: 'dashboard/subject-quizzes/',
    GRADE_PASS_FAIL_RATE: 'dashboard/grade-pass-fail-rate/',
    COMPARE_TWO_YEAR_GRADE: 'dashboard/compare-two-years-grade/',
    DIGITAL_MARKING_PROGRESS: 'student-answersheet/progress/',
    QUIZ_ANALYTICS: 'dashboard/quiz_analytics/',
    SUBJECT_PER_GRADE: "dashboard/subjects-per-grade/"
  },
  REPORT_MANAGEMENT: {
    SCHOOL_REPORT: 'reports/generate-school-report/',
    SCHOOL_TEACHER_REPORT: 'reports/school-teachers-report/',
    SCHOOL_LEARNERS_REPORT: 'reports/school-learners-report/',
    SCHOOL_PARENT_REPORT: 'reports/school-parents-report/',
    SCHOOL_ASSESSMENT_REPORT: 'reports/school-assessments-report/',
    SCHOOL_QUIZZES_REPORT: 'reports/school-quizzes-report/',
  },
  STUDY_MATERIAL: {
    LIST: 'study-material/list',
    GET_DATA_BY_ID: 'study-material/',
    ADD: 'study-material/create',
    UPDATE: 'study-material/patch/',
    DELETE: 'study-material/delete/',
  },
  GRADING_PROGRESS: {
    LIST: 'student-answersheet/filter-by-status/',
  },
  EXAME_TIMETABLE: {
    LIST: 'time-table/list',
    ADD: 'time-table/create',
    GET_DETAIL_BY_ID: '/time-table/',
    UPDATE: '/time-table/update/',
    DELETE: '/time-table/delete/',
  },
  HELP_AND_SUPPORT: {
    ADD_REPORT: 'support/add-report',
    GET_REPORT: 'support/',
    GET_REPORT_LIST: 'support/list',
  },
});

export { API };
